name: nummlk
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  random_string: ^2.3.1
  fluttertoast: ^8.2.8
  uuid: ^4.5.1
  google_sign_in: ^6.2.2
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

fonts:
  - family: Outfit
    fonts:
      - asset: fonts/Outfit-Regular.ttf

  - family: Expressa
    fonts:
      - asset: fonts/Expressa-Bold.ttf
