// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhgJmotK-TGUizcgB38HvZqm_KEXhet8',
    appId: '1:983112780196:web:43dc49c22c7bba2cbdd931',
    messagingSenderId: '983112780196',
    projectId: 'nummlk',
    authDomain: 'nummlk.firebaseapp.com',
    storageBucket: 'nummlk.firebasestorage.app',
    measurementId: 'G-850CYZQY8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIviw_EFDRj5tmTftoRI--uYz_kOIMD0Y',
    appId: '1:983112780196:android:28d8d1061bd5c94cbdd931',
    messagingSenderId: '983112780196',
    projectId: 'nummlk',
    storageBucket: 'nummlk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUnsVFZ5vwkK4tACRVHlua-LKCpfwSDhE',
    appId: '1:983112780196:ios:02021985b5cdcfaabdd931',
    messagingSenderId: '983112780196',
    projectId: 'nummlk',
    storageBucket: 'nummlk.firebasestorage.app',
    iosBundleId: 'com.example.nummlk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUnsVFZ5vwkK4tACRVHlua-LKCpfwSDhE',
    appId: '1:983112780196:ios:02021985b5cdcfaabdd931',
    messagingSenderId: '983112780196',
    projectId: 'nummlk',
    storageBucket: 'nummlk.firebasestorage.app',
    iosBundleId: 'com.example.nummlk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyhgJmotK-TGUizcgB38HvZqm_KEXhet8',
    appId: '1:983112780196:web:653038f4ec35780cbdd931',
    messagingSenderId: '983112780196',
    projectId: 'nummlk',
    authDomain: 'nummlk.firebaseapp.com',
    storageBucket: 'nummlk.firebasestorage.app',
    measurementId: 'G-MH7CQ16X5Y',
  );
}
